[package]
name = "bip32-ed25519"
version = "0.1.1"
authors = ["Shift Crypto AG <support@shiftcrypto.ch>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["no_std"]
categories = ["cryptography", "no-std"]
description = "BIP32-Ed25519"

[dependencies]
sha2 = { version = "0.10", default-features = false }
hmac = { version = "0.12", default-features = false, features = ["reset"] }
curve25519-dalek = { version = "3", default-features = false, features = ["u32_backend"] }
zeroize = { version = "1", features = ["zeroize_derive"] }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
num-bigint = "0.4.0"
# Used to test that the private keys are valid and can be used to sign messages.
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["u32_backend"] }
# Used to compare our implementation in a table test:
ed25519-bip32 = "0.4.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
hex = { version = "0.4.3", features = ["serde"] }
